# Hugging Face Token (Optional - for better API rate limits)
# Get your free token from https://huggingface.co/settings/tokens

HUGGINGFACE_TOKEN = "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"

# Note: This file should be kept private and not committed to version control
# Add .streamlit/secrets.toml to your .gitignore file